files: river
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        entry: black

      - id: isort
        name: isort
        language: python
        types: [python]
        entry: isort

      - id: ruff
        name: ruff
        language: python
        types: [python]
        entry: ruff

      - id: mypy
        name: mypy
        language: python
        types: [python]
        entry: mypy --implicit-optional

      - id: pyupgrade
        name: pyupgrade
        language: python
        types: [python]
        entry: pyupgrade --py38-plus
