[package]
name = "river_rust_stats"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "river_rust_stats"
path = "rust_src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
online-statistics = "0.2.1"
