name: check-notebooks

on:
  schedule:
    - cron: "0 0 * * FRI"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ubuntu dependencies
        run: sudo apt-get install graphviz pandoc

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[compat,dev]"
          python -m spacy download en_core_web_sm

      - name: Execute notebooks
        run: |
          pip install numpy --upgrade
          make execute-notebooks
