name: unit-tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Retrieve the environment and the River build
        uses: ./.github/actions/install-env
        with:
          python: "3.11"

      - name: Cache River datasets
        uses: actions/cache@v3
        with:
          path: ~/river_data
          key: ${{ runner.os }}

      - name: Cache scikit-learn datasets
        uses: actions/cache@v3
        with:
          path: ~/scikit_learn_data
          key: ${{ runner.os }}

      - name: Download datasets
        run: |
          source ~/.venv/bin/activate
          python -c "from river import datasets; datasets.CreditCard().download(); datasets.Elec2().download(); datasets.SMSSpam().download()"
          python -c "from river import bandit; bandit.datasets.NewsArticles().download()"

      - name: pytest [Branch]
        if: github.event_name == 'pull_request'
        run: |
          source ~/.venv/bin/activate
          pytest --durations=10 -n logical # Run pytest on all logical CPU cores

      - name: pytest [Main]
        if: github.event_name == 'push'
        run: |
          source ~/.venv/bin/activate
          pytest -m "not datasets" --durations=10 -n logical # Run pytest on all logical CPU cores
